apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deploy
  name: test-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-deploy
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - image: httpd:alpine3.19
        name: httpd
        resources: {}
status: {}