apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-test
    method: dry-run2
  name: nginx-test
spec:
  containers:
  - image: nginx
    name: nginx-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}